[package]
name = "kayring"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
clap = { version = "4.5.13", features = ["derive", "env"] }
hex = "0.4.3"
home = "0.5.9"
pbkdf2 = "0.12.2"
rpassword = "7.3.1"
sha2 = "0.10.8"
unicode-normalization = "0.1.23"
